site_name: Bitget Bot Documentation
site_dir: docs
nav:
  - Home: index.md
  - API Reference: api/core.m.html  # Links para os arquivos gerados
  - Configuração: configuration.md
  - Estratégias: strategies.md
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate